/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AbrirRouteImport } from './routes/abrir'
import { Route as CaixaRouteImport } from './routes/caixa'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as CSessionIdRouteImport } from './routes/c.$sessionId'
import { Route as CaixaIndexRouteImport } from './routes/caixa.index'
import { Route as CaixaSessionIdRouteImport } from './routes/caixa.$sessionId'
import { Route as ComandaSessionIdRouteImport } from './routes/comanda.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbrirRoute = AbrirRouteImport.update({
  id: '/abrir',
  path: '/abrir',
  getParentRoute: () => rootRouteImport,
} as any)
const CaixaRoute = CaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const CSessionIdRoute = CSessionIdRouteImport.update({
  id: '/c/$sessionId',
  path: '/c/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const CaixaIndexRoute = CaixaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaixaRoute,
} as any)
const CaixaSessionIdRoute = CaixaSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => CaixaRoute,
} as any)
const ComandaSessionIdRoute = ComandaSessionIdRouteImport.update({
  id: '/comanda/$sessionId',
  path: '/comanda/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abrir': typeof AbrirRoute
  '/caixa': typeof CaixaRouteWithChildren
  '/equipe': typeof EquipeRoute
  '/c/$sessionId': typeof CSessionIdRoute
  '/caixa/$sessionId': typeof CaixaSessionIdRoute
  '/comanda/$sessionId': typeof ComandaSessionIdRoute
  '/caixa/': typeof CaixaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abrir': typeof AbrirRoute
  '/equipe': typeof EquipeRoute
  '/c/$sessionId': typeof CSessionIdRoute
  '/caixa/$sessionId': typeof CaixaSessionIdRoute
  '/comanda/$sessionId': typeof ComandaSessionIdRoute
  '/caixa': typeof CaixaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abrir': typeof AbrirRoute
  '/caixa': typeof CaixaRouteWithChildren
  '/equipe': typeof EquipeRoute
  '/c/$sessionId': typeof CSessionIdRoute
  '/caixa/$sessionId': typeof CaixaSessionIdRoute
  '/comanda/$sessionId': typeof ComandaSessionIdRoute
  '/caixa/': typeof CaixaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abrir'
    | '/caixa'
    | '/equipe'
    | '/c/$sessionId'
    | '/caixa/$sessionId'
    | '/comanda/$sessionId'
    | '/caixa/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abrir'
    | '/equipe'
    | '/c/$sessionId'
    | '/caixa/$sessionId'
    | '/comanda/$sessionId'
    | '/caixa'
  id:
    | '__root__'
    | '/'
    | '/abrir'
    | '/caixa'
    | '/equipe'
    | '/c/$sessionId'
    | '/caixa/$sessionId'
    | '/comanda/$sessionId'
    | '/caixa/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbrirRoute: typeof AbrirRoute
  CaixaRoute: typeof CaixaRouteWithChildren
  EquipeRoute: typeof EquipeRoute
  CSessionIdRoute: typeof CSessionIdRoute
  ComandaSessionIdRoute: typeof ComandaSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abrir': {
      id: '/abrir'
      path: '/abrir'
      fullPath: '/abrir'
      preLoaderRoute: typeof AbrirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caixa': {
      id: '/caixa'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof CaixaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$sessionId': {
      id: '/c/$sessionId'
      path: '/c/$sessionId'
      fullPath: '/c/$sessionId'
      preLoaderRoute: typeof CSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caixa/': {
      id: '/caixa/'
      path: '/'
      fullPath: '/caixa/'
      preLoaderRoute: typeof CaixaIndexRouteImport
      parentRoute: typeof CaixaRoute
    }
    '/caixa/$sessionId': {
      id: '/caixa/$sessionId'
      path: '/$sessionId'
      fullPath: '/caixa/$sessionId'
      preLoaderRoute: typeof CaixaSessionIdRouteImport
      parentRoute: typeof CaixaRoute
    }
    '/comanda/$sessionId': {
      id: '/comanda/$sessionId'
      path: '/comanda/$sessionId'
      fullPath: '/comanda/$sessionId'
      preLoaderRoute: typeof ComandaSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CaixaRouteChildren {
  CaixaSessionIdRoute: typeof CaixaSessionIdRoute
  CaixaIndexRoute: typeof CaixaIndexRoute
}

const CaixaRouteChildren: CaixaRouteChildren = {
  CaixaSessionIdRoute: CaixaSessionIdRoute,
  CaixaIndexRoute: CaixaIndexRoute,
}

const CaixaRouteWithChildren = CaixaRoute._addFileChildren(CaixaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbrirRoute: AbrirRoute,
  CaixaRoute: CaixaRouteWithChildren,
  EquipeRoute: EquipeRoute,
  CSessionIdRoute: CSessionIdRoute,
  ComandaSessionIdRoute: ComandaSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
