/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AbrirRouteImport } from './routes/abrir'
import { Route as CaixaRouteImport } from './routes/caixa'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as CSessionIdRouteImport } from './routes/c.$sessionId'
import { Route as CaixaIndexRouteImport } from './routes/caixa.index'
import { Route as CaixaSessionIdRouteImport } from './routes/caixa.$sessionId'
import { Route as CaixaAlertasRouteImport } from './routes/caixa.alertas'
import { Route as CaixaCardapioRouteImport } from './routes/caixa.cardapio'
import { Route as CaixaCrmRouteImport } from './routes/caixa.crm'
import { Route as CaixaEstoqueRouteImport } from './routes/caixa.estoque'
import { Route as CaixaRelatoriosRouteImport } from './routes/caixa.relatorios'
import { Route as ComandaSessionIdRouteImport } from './routes/comanda.$sessionId'
import { Route as CSessionIdPerfilRouteImport } from './routes/c.$sessionId_.perfil'
import { Route as CaixaCrmIndexRouteImport } from './routes/caixa.crm.index'
import { Route as CaixaCrmClientesRouteImport } from './routes/caixa.crm.clientes'
import { Route as CaixaCrmClientesCustomerIdRouteImport } from './routes/caixa.crm.clientes_.$customerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbrirRoute = AbrirRouteImport.update({
  id: '/abrir',
  path: '/abrir',
  getParentRoute: () => rootRouteImport,
} as any)
const CaixaRoute = CaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const CSessionIdRoute = CSessionIdRouteImport.update({
  id: '/c/$sessionId',
  path: '/c/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const CaixaIndexRoute = CaixaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaixaRoute,
} as any)
const CaixaSessionIdRoute = CaixaSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => CaixaRoute,
} as any)
const CaixaAlertasRoute = CaixaAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => CaixaRoute,
} as any)
const CaixaCardapioRoute = CaixaCardapioRouteImport.update({
  id: '/cardapio',
  path: '/cardapio',
  getParentRoute: () => CaixaRoute,
} as any)
const CaixaCrmRoute = CaixaCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => CaixaRoute,
} as any)
const CaixaEstoqueRoute = CaixaEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => CaixaRoute,
} as any)
const CaixaRelatoriosRoute = CaixaRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => CaixaRoute,
} as any)
const ComandaSessionIdRoute = ComandaSessionIdRouteImport.update({
  id: '/comanda/$sessionId',
  path: '/comanda/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const CSessionIdPerfilRoute = CSessionIdPerfilRouteImport.update({
  id: '/c/$sessionId_/perfil',
  path: '/c/$sessionId/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const CaixaCrmIndexRoute = CaixaCrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaixaCrmRoute,
} as any)
const CaixaCrmClientesRoute = CaixaCrmClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => CaixaCrmRoute,
} as any)
const CaixaCrmClientesCustomerIdRoute =
  CaixaCrmClientesCustomerIdRouteImport.update({
    id: '/clientes_/$customerId',
    path: '/clientes/$customerId',
    getParentRoute: () => CaixaCrmRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abrir': typeof AbrirRoute
  '/caixa': typeof CaixaRouteWithChildren
  '/equipe': typeof EquipeRoute
  '/c/$sessionId': typeof CSessionIdRoute
  '/caixa/$sessionId': typeof CaixaSessionIdRoute
  '/caixa/alertas': typeof CaixaAlertasRoute
  '/caixa/cardapio': typeof CaixaCardapioRoute
  '/caixa/crm': typeof CaixaCrmRouteWithChildren
  '/caixa/estoque': typeof CaixaEstoqueRoute
  '/caixa/relatorios': typeof CaixaRelatoriosRoute
  '/comanda/$sessionId': typeof ComandaSessionIdRoute
  '/caixa/': typeof CaixaIndexRoute
  '/c/$sessionId/perfil': typeof CSessionIdPerfilRoute
  '/caixa/crm/clientes': typeof CaixaCrmClientesRoute
  '/caixa/crm/': typeof CaixaCrmIndexRoute
  '/caixa/crm/clientes/$customerId': typeof CaixaCrmClientesCustomerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abrir': typeof AbrirRoute
  '/equipe': typeof EquipeRoute
  '/c/$sessionId': typeof CSessionIdRoute
  '/caixa/$sessionId': typeof CaixaSessionIdRoute
  '/caixa/alertas': typeof CaixaAlertasRoute
  '/caixa/cardapio': typeof CaixaCardapioRoute
  '/caixa/estoque': typeof CaixaEstoqueRoute
  '/caixa/relatorios': typeof CaixaRelatoriosRoute
  '/comanda/$sessionId': typeof ComandaSessionIdRoute
  '/caixa': typeof CaixaIndexRoute
  '/c/$sessionId/perfil': typeof CSessionIdPerfilRoute
  '/caixa/crm/clientes': typeof CaixaCrmClientesRoute
  '/caixa/crm': typeof CaixaCrmIndexRoute
  '/caixa/crm/clientes/$customerId': typeof CaixaCrmClientesCustomerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abrir': typeof AbrirRoute
  '/caixa': typeof CaixaRouteWithChildren
  '/equipe': typeof EquipeRoute
  '/c/$sessionId': typeof CSessionIdRoute
  '/caixa/$sessionId': typeof CaixaSessionIdRoute
  '/caixa/alertas': typeof CaixaAlertasRoute
  '/caixa/cardapio': typeof CaixaCardapioRoute
  '/caixa/crm': typeof CaixaCrmRouteWithChildren
  '/caixa/estoque': typeof CaixaEstoqueRoute
  '/caixa/relatorios': typeof CaixaRelatoriosRoute
  '/comanda/$sessionId': typeof ComandaSessionIdRoute
  '/caixa/': typeof CaixaIndexRoute
  '/c/$sessionId_/perfil': typeof CSessionIdPerfilRoute
  '/caixa/crm/clientes': typeof CaixaCrmClientesRoute
  '/caixa/crm/': typeof CaixaCrmIndexRoute
  '/caixa/crm/clientes_/$customerId': typeof CaixaCrmClientesCustomerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abrir'
    | '/caixa'
    | '/equipe'
    | '/c/$sessionId'
    | '/caixa/$sessionId'
    | '/caixa/alertas'
    | '/caixa/cardapio'
    | '/caixa/crm'
    | '/caixa/estoque'
    | '/caixa/relatorios'
    | '/comanda/$sessionId'
    | '/caixa/'
    | '/c/$sessionId/perfil'
    | '/caixa/crm/clientes'
    | '/caixa/crm/'
    | '/caixa/crm/clientes/$customerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abrir'
    | '/equipe'
    | '/c/$sessionId'
    | '/caixa/$sessionId'
    | '/caixa/alertas'
    | '/caixa/cardapio'
    | '/caixa/estoque'
    | '/caixa/relatorios'
    | '/comanda/$sessionId'
    | '/caixa'
    | '/c/$sessionId/perfil'
    | '/caixa/crm/clientes'
    | '/caixa/crm'
    | '/caixa/crm/clientes/$customerId'
  id:
    | '__root__'
    | '/'
    | '/abrir'
    | '/caixa'
    | '/equipe'
    | '/c/$sessionId'
    | '/caixa/$sessionId'
    | '/caixa/alertas'
    | '/caixa/cardapio'
    | '/caixa/crm'
    | '/caixa/estoque'
    | '/caixa/relatorios'
    | '/comanda/$sessionId'
    | '/caixa/'
    | '/c/$sessionId_/perfil'
    | '/caixa/crm/clientes'
    | '/caixa/crm/'
    | '/caixa/crm/clientes_/$customerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbrirRoute: typeof AbrirRoute
  CaixaRoute: typeof CaixaRouteWithChildren
  EquipeRoute: typeof EquipeRoute
  CSessionIdRoute: typeof CSessionIdRoute
  ComandaSessionIdRoute: typeof ComandaSessionIdRoute
  CSessionIdPerfilRoute: typeof CSessionIdPerfilRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abrir': {
      id: '/abrir'
      path: '/abrir'
      fullPath: '/abrir'
      preLoaderRoute: typeof AbrirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caixa': {
      id: '/caixa'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof CaixaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$sessionId': {
      id: '/c/$sessionId'
      path: '/c/$sessionId'
      fullPath: '/c/$sessionId'
      preLoaderRoute: typeof CSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caixa/': {
      id: '/caixa/'
      path: '/'
      fullPath: '/caixa/'
      preLoaderRoute: typeof CaixaIndexRouteImport
      parentRoute: typeof CaixaRoute
    }
    '/caixa/$sessionId': {
      id: '/caixa/$sessionId'
      path: '/$sessionId'
      fullPath: '/caixa/$sessionId'
      preLoaderRoute: typeof CaixaSessionIdRouteImport
      parentRoute: typeof CaixaRoute
    }
    '/caixa/alertas': {
      id: '/caixa/alertas'
      path: '/alertas'
      fullPath: '/caixa/alertas'
      preLoaderRoute: typeof CaixaAlertasRouteImport
      parentRoute: typeof CaixaRoute
    }
    '/caixa/cardapio': {
      id: '/caixa/cardapio'
      path: '/cardapio'
      fullPath: '/caixa/cardapio'
      preLoaderRoute: typeof CaixaCardapioRouteImport
      parentRoute: typeof CaixaRoute
    }
    '/caixa/crm': {
      id: '/caixa/crm'
      path: '/crm'
      fullPath: '/caixa/crm'
      preLoaderRoute: typeof CaixaCrmRouteImport
      parentRoute: typeof CaixaRoute
    }
    '/caixa/estoque': {
      id: '/caixa/estoque'
      path: '/estoque'
      fullPath: '/caixa/estoque'
      preLoaderRoute: typeof CaixaEstoqueRouteImport
      parentRoute: typeof CaixaRoute
    }
    '/caixa/relatorios': {
      id: '/caixa/relatorios'
      path: '/relatorios'
      fullPath: '/caixa/relatorios'
      preLoaderRoute: typeof CaixaRelatoriosRouteImport
      parentRoute: typeof CaixaRoute
    }
    '/comanda/$sessionId': {
      id: '/comanda/$sessionId'
      path: '/comanda/$sessionId'
      fullPath: '/comanda/$sessionId'
      preLoaderRoute: typeof ComandaSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$sessionId_/perfil': {
      id: '/c/$sessionId_/perfil'
      path: '/c/$sessionId/perfil'
      fullPath: '/c/$sessionId/perfil'
      preLoaderRoute: typeof CSessionIdPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caixa/crm/': {
      id: '/caixa/crm/'
      path: '/'
      fullPath: '/caixa/crm/'
      preLoaderRoute: typeof CaixaCrmIndexRouteImport
      parentRoute: typeof CaixaCrmRoute
    }
    '/caixa/crm/clientes': {
      id: '/caixa/crm/clientes'
      path: '/clientes'
      fullPath: '/caixa/crm/clientes'
      preLoaderRoute: typeof CaixaCrmClientesRouteImport
      parentRoute: typeof CaixaCrmRoute
    }
    '/caixa/crm/clientes_/$customerId': {
      id: '/caixa/crm/clientes_/$customerId'
      path: '/clientes/$customerId'
      fullPath: '/caixa/crm/clientes/$customerId'
      preLoaderRoute: typeof CaixaCrmClientesCustomerIdRouteImport
      parentRoute: typeof CaixaCrmRoute
    }
  }
}

interface CaixaCrmRouteChildren {
  CaixaCrmClientesRoute: typeof CaixaCrmClientesRoute
  CaixaCrmIndexRoute: typeof CaixaCrmIndexRoute
  CaixaCrmClientesCustomerIdRoute: typeof CaixaCrmClientesCustomerIdRoute
}

const CaixaCrmRouteChildren: CaixaCrmRouteChildren = {
  CaixaCrmClientesRoute: CaixaCrmClientesRoute,
  CaixaCrmIndexRoute: CaixaCrmIndexRoute,
  CaixaCrmClientesCustomerIdRoute: CaixaCrmClientesCustomerIdRoute,
}

const CaixaCrmRouteWithChildren = CaixaCrmRoute._addFileChildren(
  CaixaCrmRouteChildren,
)

interface CaixaRouteChildren {
  CaixaSessionIdRoute: typeof CaixaSessionIdRoute
  CaixaAlertasRoute: typeof CaixaAlertasRoute
  CaixaCardapioRoute: typeof CaixaCardapioRoute
  CaixaCrmRoute: typeof CaixaCrmRouteWithChildren
  CaixaEstoqueRoute: typeof CaixaEstoqueRoute
  CaixaRelatoriosRoute: typeof CaixaRelatoriosRoute
  CaixaIndexRoute: typeof CaixaIndexRoute
}

const CaixaRouteChildren: CaixaRouteChildren = {
  CaixaSessionIdRoute: CaixaSessionIdRoute,
  CaixaAlertasRoute: CaixaAlertasRoute,
  CaixaCardapioRoute: CaixaCardapioRoute,
  CaixaCrmRoute: CaixaCrmRouteWithChildren,
  CaixaEstoqueRoute: CaixaEstoqueRoute,
  CaixaRelatoriosRoute: CaixaRelatoriosRoute,
  CaixaIndexRoute: CaixaIndexRoute,
}

const CaixaRouteWithChildren = CaixaRoute._addFileChildren(CaixaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbrirRoute: AbrirRoute,
  CaixaRoute: CaixaRouteWithChildren,
  EquipeRoute: EquipeRoute,
  CSessionIdRoute: CSessionIdRoute,
  ComandaSessionIdRoute: ComandaSessionIdRoute,
  CSessionIdPerfilRoute: CSessionIdPerfilRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
